aur_dict = {
    "a": "aurek",
    "b": "besh",
    "c": "cresh",
    "d": "dorn",
    "w": "wesk",  # Si se coloca después de 'e' puede dar lugar a errores en la traduccion aure > spa
    "e": "esk",
    "f": "forn",
    "g": "grek",
    "h": "herf",
    "i": "isk",
    "j": "jenth",
    "k": "krill",
    "l": "leth",
    "m": "mern",
    "n": "nern",
    "o": "osk",
    "p": "peth",
    "q": "qek",
    "r": "resh",
    "s": "senth",
    "t": "trill",
    "u": "usk",
    "v": "vev",
    "x": "xesh",
    "y": "yirt",
    "z": "zerek",
    "ch": "cherek",
    "ae": "enth",
    "eo": "onith",
    "kh": "krenth",
    "ng": "nen",
    "oo": "orenth",
    "sh": "shen",
    "th": "thesh",
}
